import {
	STR, DEX, CON, WIS, INT, CHA,
	ACROBATICS, ANIMAL_HANDLING, ATHLETICS, DECEPTION, HISTORY,
	INSIGHT, INTIMIDATION, INVESTIGATION, MEDICINE, NATURE,
	PERCEPTION, PERFORMANCE, PERSUASION, RELIGION, SCIENCE,
	SLEIGHT_OF_HAND, STEALTH, SURVIVAL,
} from 'constants/schema'

export const alignments = [
	'Lawful Good',
	'Neutral Good',
	'Chaotic Good',
	'Lawful Neutral',
	'True Neutral',
	'Chaotic Neutral',
	'Lawful Evil',
	'Neutral Evil',
	'Chaotic Evil',
]

export const attributes = [
	STR, DEX, CON, WIS, INT, CHA,
]

export const skills = [
	ACROBATICS, ANIMAL_HANDLING, ATHLETICS, DECEPTION, HISTORY,
	INSIGHT, INTIMIDATION, INVESTIGATION, MEDICINE, NATURE, 
	PERCEPTION, PERFORMANCE, PERSUASION, RELIGION, SCIENCE,
	SLEIGHT_OF_HAND, STEALTH, SURVIVAL,
]
